apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  labels:
    app: patient
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient
  template:
    metadata:
      labels:
        app: patient
    spec:
      containers:
        - name: patient-service
          image: <your-aws-account-id>.dkr.ecr.<your-region>.amazonaws.com/patient-service:latest
          ports:
            - containerPort: 3002

