name: Docker Build and Push Images

on:
  workflow_dispatch:  # Trigger manually

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::116981791124:role/idp-role
          aws-region: us-west-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 116981791124.dkr.ecr.us-west-1.amazonaws.com
      - name: Create ECR Repository (if it doesn't exist)
        run: |
          aws ecr describe-repositories --repository-names my-services --region us-west-1 || \
          aws ecr create-repository --repository-name my-services --region us-west-1
      - name: Build and Push Appointment Service Image
        run: |
          # Build Docker image for Appointment Service
          docker build -t appointment-service ./app/appointment-service
          # Tag the image with the repository and specific tag
          docker tag appointment-service:latest 116981791124.dkr.ecr.us-west-1.amazonaws.com/my-services:appointment-service-latest
          # Push the image to ECR
          docker push 116981791124.dkr.ecr.us-west-1.amazonaws.com/my-services:appointment-service-latest
      - name: Build and Push Patient Service Image
        run: |
          # Build Docker image for Patient Service
          docker build -t patient-service ./app/patient-service
          # Tag the image with the repository and specific tag
          docker tag patient-service:latest 116981791124.dkr.ecr.us-west-1.amazonaws.com/my-services:patient-service-latest
          # Push the image to ECR
          docker push 116981791124.dkr.ecr.us-west-1.amazonaws.com/my-services:patient-service-latest
